version: '3.8'

services:
  db:
    image: "postgres:latest"
    container_name: db
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: 'notes-backend'
    build:
      context: .
    container_name: app-notes
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}

  vite-app:
    build:
      context: ../express
    container_name: vite-app
    ports:
      - "9090:9090"
    depends_on:
      - app

volumes:
  postgres_data:
